# Jobs that run on push to main, after pull requests are merged.

on:
    push:
        branches:
            - main

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false

            - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
              with:
                  key: cargo-${{ hashFiles('**/Cargo.lock') }}
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  restore-keys: |
                      cargo-

            - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

            - run: rustup component add rustfmt

            - run: just build
